module.exports = {
  caseType:'versioned_medical_device_change_control', initialState:'device_baseline',
  states:['device_baseline','intended_use_classified','traceability_review','risk_review','vv_evidence_review','submission_review','qualified_approved','released','postmarket_change','recall_review','closed'],
  createRoles:['design_owner','quality_engineer'],
  assessmentRoles:['quality_engineer','regulatory_specialist','risk_manager','post_market_owner'],
  auditRoles:['quality_manager','regulatory_specialist','auditor'],
  connectorRoles:['quality_manager','integration_operator'],
  evidenceKinds:['device_version_manifest','intended_use_classification','user_need_requirement_trace','hazard_control_trace','risk_file_version','verification_validation_digest','deviation_capa_record','sbom_cybersecurity_snapshot','supplier_record','complaint_record','submission_package_manifest','electronic_signature','recall_record'],
  requiredSignals:['deviceVersion','intendedUseVersion','market','jurisdictionRuleVersion','ruleEffectiveAt','riskVersion','traceabilityCoverage','vvStatus','policyVersion'],
  professionalBoundary:'Checks are administrative decision support, not regulatory, quality, clinical, safety, legal, or submission approval; qualified independent reviewers sign.',
  connectors:[
    {name:'eqms_document',purpose:'controlled document and QMS versions'},
    {name:'complaint',purpose:'post-market complaint references'},
    {name:'supplier',purpose:'qualified supplier status'},
    {name:'sbom_cybersecurity',purpose:'SBOM and vulnerability snapshots'},
    {name:'test_lab',purpose:'signed test evidence'},
    {name:'regulatory_submission',purpose:'submission receipts only'},
  ],
  transitions:[
    {from:'device_baseline',action:'classify_intended_use',to:'intended_use_classified',roles:['design_owner','regulatory_specialist'],requiresEvidence:true},
    {from:'intended_use_classified',action:'review_traceability',to:'traceability_review',roles:['quality_engineer'],requiresEvidence:true},
    {from:'traceability_review',action:'review_risk',to:'risk_review',roles:['risk_manager'],requiresEvidence:true,dualControl:true},
    {from:'risk_review',action:'review_vv',to:'vv_evidence_review',roles:['quality_engineer'],requiresEvidence:true},
    {from:'vv_evidence_review',action:'review_submission',to:'submission_review',roles:['regulatory_specialist'],requiresEvidence:true,dualControl:true},
    {from:'submission_review',action:'approve',to:'qualified_approved',roles:['quality_manager','independent_approver'],requiresEvidence:true,dualControl:true},
    {from:'qualified_approved',action:'release',to:'released',roles:['quality_manager'],requiresEvidence:true,dualControl:true},
    {from:'released',action:'open_postmarket_change',to:'postmarket_change',roles:['post_market_owner'],requiresEvidence:true},
    {from:'postmarket_change',action:'open_recall_review',to:'recall_review',roles:['post_market_owner','quality_manager'],requiresEvidence:true},
    {from:'recall_review',action:'close',to:'closed',roles:['quality_manager','regulatory_specialist'],requiresEvidence:true,dualControl:true},
  ],
  assess:x=>{const market=['US_FDA','EU_MDR','EU_IVDR'].includes(x.market);const effective=!Number.isNaN(Date.parse(x.ruleEffectiveAt));const coverage=Number(x.traceabilityCoverage);const valid=Number.isFinite(coverage)&&coverage>=0&&coverage<=100;return{disposition:market&&effective&&valid&&coverage===100&&x.vvStatus==='verified'?'qualified_regulatory_review_required':'evidence_or_jurisdiction_hold',regulatoryDecision:null,authoritativeCitation:null,versions:{device:x.deviceVersion,intendedUse:x.intendedUseVersion,risk:x.riskVersion,rules:x.jurisdictionRuleVersion}};},
};
