const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {createWorkflow}=require('./workflowCore');const {validateRuntime}=require('./runtime');const config=require('./config');const workflow=createWorkflow(config);const headers={'x-tenant-id':'manufacturer-a','idempotency-key':'request-a'};
const accepted={deviceVersion:'device-v4',intendedUseVersion:'use-v2',market:'US_FDA',jurisdictionRuleVersion:'rules-v7',ruleEffectiveAt:'2026-01-01',riskVersion:'risk-v3',traceabilityCoverage:100,vvStatus:'verified',policyVersion:'policy-v1'};
test('device change-control topology and controlled connectors are declared',()=>{assert.ok(config.states.includes(config.initialState));assert.ok(config.transitions.length>2);assert.ok(config.connectors.length>2);for(const r of config.transitions){assert.ok(config.states.includes(r.from));assert.ok(config.states.includes(r.to));assert.ok(r.roles.length);}});
test('tenant, idempotency, actor and qualified role boundaries fail closed',()=>{assert.throws(()=>workflow.context({}, {id:'a',role:'quality_engineer'}),/X-Tenant-Id/);const c=workflow.context(headers,{id:'quality-a',role:'quality_engineer'});assert.equal(workflow.createCase({subjectRef:'device-change-17',policyVersion:'p-v1',effectiveAt:'2026-07-18T00:00:00Z'},c).state,config.initialState);assert.throws(()=>workflow.createCase({subjectRef:'device-change-17',policyVersion:'p-v1',effectiveAt:'2026-07-18T00:00:00Z'},{...c,role:'visitor'}),/Role cannot create/);});
test('controlled evidence is opaque and digest verified',()=>{assert.equal(workflow.evidence({kind:config.evidenceKinds[0],sourceRef:'eqms:device-17',sourceVersion:'v1',sha256:'a'.repeat(64),capturedAt:'2026-07-18T10:00:00Z'}).sha256,'a'.repeat(64));assert.throws(()=>workflow.evidence({kind:config.evidenceKinds[0],sourceRef:'eqms:x',sourceVersion:'v1',sha256:'bad',capturedAt:'2026-07-18T10:00:00Z'}),/sha256/);});
test('complete traceability requires qualified review and missing evidence holds',()=>{const c=workflow.context(headers,{id:'quality-a',role:'quality_engineer'});assert.equal(workflow.deterministicAssessment({},c).disposition,'insufficient_evidence');const good=workflow.deterministicAssessment(accepted,c);assert.equal(good.disposition,'qualified_regulatory_review_required');assert.equal(good.regulatoryDecision,null);assert.equal(good.authoritativeCitation,null);assert.equal(good.automatedDecision,false);assert.equal(workflow.deterministicAssessment({...accepted,traceabilityCoverage:99},c).disposition,'evidence_or_jurisdiction_hold');});
test('transitions require evidence, versions, segregation and signatures',()=>{const r=config.transitions[0];const c=workflow.context(headers,{id:'actor-b',role:r.roles[0]});const rec={state:r.from,version:1,evidenceCount:0,createdBy:'actor-a',lastActorId:null};assert.throws(()=>workflow.transition(rec,{action:r.action,expectedVersion:1,reason:'classified intended use evidence'},c),/evidence/);assert.throws(()=>workflow.transition({...rec,evidenceCount:1},{action:r.action,expectedVersion:2,reason:'classified intended use evidence'},c),/changed/);assert.equal(workflow.transition({...rec,evidenceCount:1},{action:r.action,expectedVersion:1,reason:'classified intended use evidence'},c).to,r.to);const d=config.transitions.find(x=>x.dualControl);const dc=workflow.context(headers,{id:'actor-b',role:d.roles[0]});assert.throws(()=>workflow.transition({state:d.from,version:2,evidenceCount:1,createdBy:'actor-a',lastActorId:'actor-b'},{action:d.action,expectedVersion:2,reason:'independent quality approval'},dc),/second person/);});
test('runtime safety rejects weak or demo production config',()=>{assert.throws(()=>validateRuntime({NODE_ENV:'test',JWT_SECRET:'short'}),/JWT_SECRET/);assert.throws(()=>validateRuntime({NODE_ENV:'production',JWT_SECRET:'x'.repeat(40),DATABASE_URL:'postgres://configured',CORS_ORIGINS:'*'}),/allowlist/);assert.throws(()=>validateRuntime({NODE_ENV:'production',JWT_SECRET:'x'.repeat(40),DATABASE_URL:'postgres://configured',CORS_ORIGINS:'https://client.example',ALLOW_MOCK_PROVIDERS:'true'}),/prohibited/);assert.equal(validateRuntime({NODE_ENV:'test',JWT_SECRET:'x'.repeat(40)}),true);});
test('migration and launcher are append-only and nondestructive',()=>{const root=path.resolve(__dirname,'..','..');const m=fs.readFileSync(path.join(root,'server/migrations/001_governed_device_compliance.sql'),'utf8');const s=fs.readFileSync(path.join(root,'start.sh'),'utf8');assert.match(m,/governed_tenant_memberships/);assert.match(m,/governed_connector_failures/);assert.match(m,/append-only/);assert.doesNotMatch(s,/kill\s+-9|pkill|dropdb|createdb|npm\s+install|seed\.js|psql\s+.*-f/);});
